wishters_blog_homepage:
    path:     /
    defaults: { _controller: WishtersBlogBundle:Blog:index }

wishters_blog_post_traitement:
    path:     /traitement
    defaults: { _controller: WishtersBlogBundle:Blog:postTraitement }

wishters_blog_fade_post:
    path: /fade-post/{id}
    defaults: { _controller: WishtersBlogBundle:Blog:fadePosts }
    requirements:
        id: \d+